apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xiangjiandao.fullname" . }}
  labels:
    {{- include "xiangjiandao.labels" . | nindent 4 }}
data:
  appconfig.json: |
    {{ .Values.appconfig | nindent 4 }}
