apiVersion: v1
kind: Service
metadata:
  name: {{ include "xiangjiandao.fullname" . }}
  labels:
    app: {{ include "xiangjiandao.name" . }}
    {{- include "xiangjiandao.labels" . | nindent 4 }}
    {{- if .Values.env.envName }}
    env: {{ .Values.env.envName }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xiangjiandao.selectorLabels" . | nindent 4 }}
